name: default

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest

    container: 'node:14'

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      # - name: Audit
      #   run: npm audit --audit-level=high

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Install dependencies from lock.
        run: npm ci

      - name: Linter.
        run: npm run lint:ci

      - name: Unit tests.
        run: npm run test:cov

      # - name: E2E tests.
      #   run: npm run test:e2e

      - name: Build source code.
        run: npm run build
